import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Film, Lock, ShieldCheck, Sparkles, BrainCircuit, Clapperboard } from "lucide-react";
import MarketingHeader from "../components/MarketingHeader";
import aboutHero from "../assets/about_hero.png";
import ckriptVideo from "../assets/ckript-video.mp4";

const FontInjection = () => (
	<style>{`
		@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;0,9..144,900;1,9..144,400;1,9..144,500;1,9..144,700&family=Inter:wght@300;400;500;600;700&display=swap');

		.font-display { font-family: 'Fraunces', Georgia, serif; font-optical-sizing: auto; }
		.font-body { font-family: 'Inter', system-ui, sans-serif; }

		.grain::before {
			content: '';
			position: absolute;
			inset: 0;
			pointer-events: none;
			opacity: 0.05;
			mix-blend-mode: overlay;
			background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
		}

		.about-glow {
			position: absolute;
			border-radius: 9999px;
			filter: blur(68px);
			opacity: 0.42;
			pointer-events: none;
		}
	`}</style>
);

const securityPoints = [
	{
		title: "Secure, Locked Storage",
		description:
			"Every script uploaded to Ckript is hosted in a fully secure, state-of-the-art environment. Access is strictly controlled, ensuring that your work remains locked and confidential.",
	},
	{
		title: "Chain of Title Assurance",
		description:
			"Our platform's security architecture is built to explicitly preserve ownership and originality. Writers maintain full control over who can view their material, ensuring intellectual property rights are protected.",
	},
	{
		title: "Comprehensive Encryption",
		description:
			"Ckript utilizes advanced encryption protocols (both in transit and at rest) to safeguard sensitive script data against unauthorized access, providing writers with unconditional peace of mind throughout the submission process.",
	},
];

const discoveryPoints = [
	{
		title: "Dynamic AI Trailers",
		description:
			"Instead of reviewing lengthy loglines and scripts manually, producers can immediately assess a project's tone, genre, and cinematic potential through AI-generated trailers that summarize key narrative beats visually.",
	},
	{
		title: "AI-Based Evaluation Scores",
		description:
			"Our platform utilizes advanced analytics to generate comprehensive evaluation scores. These insights provide objective feedback on a script's narrative structure, character development, dialogue, and marketability, enabling producers to filter submissions effectively.",
	},
	{
		title: "Concise Digital Coverage",
		description:
			"Producers can quickly digest short descriptions and professional insights generated by the platform, allowing them to rapidly identify material that aligns with their production needs and creative vision.",
	},
];

function ContentCard({ icon: Icon, title, description }) {
	return (
		<article className="rounded-2xl border border-[#2a3d59] bg-[linear-gradient(145deg,#0f1a2d_0%,#0d1728_56%,#12233a_100%)] p-4 sm:p-5 shadow-[0_12px_28px_rgba(2,8,24,0.42)]">
			<div className="mb-3 inline-flex h-9 w-9 items-center justify-center rounded-lg border border-[#3b5677] bg-[#14253c]">
				<Icon className="h-4.5 w-4.5 text-[#c9def6]" />
			</div>
			<h3 className="font-body text-base font-semibold text-[#F8FAFC]">{title}</h3>
			<p className="font-body mt-2 text-sm leading-relaxed text-[#b4c4d8]">{description}</p>
		</article>
	);
}

const About = () => {
	return (
		<div className="relative min-h-screen overflow-x-hidden bg-white text-[#0f172a]">
			<FontInjection />
			<div className="pointer-events-none fixed inset-0 z-0">
				<div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_10%,rgba(99,102,241,0.10),transparent_34%),radial-gradient(circle_at_84%_12%,rgba(59,130,246,0.12),transparent_38%)]" />
				<div className="about-glow left-[-120px] top-[200px] h-[320px] w-[320px] bg-[#93c5fd]" />
				<div className="about-glow right-[-90px] top-[80px] h-[280px] w-[280px] bg-[#c4b5fd]" />
			</div>

			<MarketingHeader />

			<section className="relative z-10 px-4 pb-12 pt-28 sm:px-8 sm:pb-16 sm:pt-32">
				<div className="mx-auto w-full max-w-6xl">
					<p className="font-body flex w-full justify-center text-center px-4 py-1.5 text-[32px] font-bold uppercase tracking-[0.16em] text-black sm:text-[40px]">
						About Ckript
					</p>

					<div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-5 lg:gap-10">
						<motion.div
							initial={{ opacity: 0, y: 12 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.45 }}
							className="lg:col-span-3"
						>
							<h1 className="font-display text-[#0f172a] text-3xl leading-[0.98] tracking-tight sm:text-5xl">
								Secure, intelligent script discovery for creators and industry professionals.
							</h1>
							<p className="font-body mt-5 text-sm leading-relaxed text-[#334155] sm:text-base">
								Ckript is the premier secure, end-to-end marketplace revolutionizing the connection between independent screenwriters and film industry professionals. We offer a sophisticated ecosystem designed to streamline script discovery, enhance intellectual property protection, and foster successful collaborations.
							</p>
							<p className="font-body mt-3 text-sm leading-relaxed text-[#334155] sm:text-base">
								Our mission is to empower writers by safeguarding their work while providing producers and directors with powerful, intelligent tools to efficiently identify and acquire high-quality, relevant material for their upcoming creative projects.
							</p>
						</motion.div>

						<motion.div
							initial={{ opacity: 0, y: 14 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.45, delay: 0.1 }}
							className="overflow-hidden rounded-3xl bg-[#0d1b2e] shadow-[0_22px_40px_rgba(3,10,26,0.5)] lg:col-span-2"
						>
							<img
								src={aboutHero}
								alt="Ckript marketplace visual"
								className="h-full min-h-[250px] w-full object-cover"
								loading="eager"
							/>
						</motion.div>
					</div>
				</div>
			</section>

			<section className="relative z-10 px-4 pb-10 sm:px-8 sm:pb-14">
				<div className="mx-auto w-full max-w-6xl overflow-hidden rounded-3xl border border-[#29405c] bg-[#0f1a2d] shadow-[0_22px_40px_rgba(3,10,26,0.5)]">
					<div className="border-b border-[#2b425f] bg-[linear-gradient(115deg,#0d1a2f_0%,#1b3a5d_48%,#2e5f8f_100%)] px-5 py-4 sm:px-7 sm:py-5">
						<h2 className="font-display text-2xl text-white sm:text-3xl">How to Use the Platform</h2>
						<p className="font-body mt-2 text-sm leading-relaxed text-[#d6e4f3] sm:text-base">
							Watch this quick walkthrough to understand how writers can upload securely and how producers can discover and evaluate scripts efficiently.
						</p>
					</div>
					<video
						controls
						controlsList="nodownload"
						playsInline
						preload="metadata"
						className="h-full max-h-[560px] w-full bg-black/90"
						aria-label="How to use Ckript platform video"
					>
						<source src={ckriptVideo} type="video/mp4" />
						Your browser does not support the video tag.
					</video>
				</div>
			</section>

			<section className="relative z-10 px-4 pb-10 sm:px-8 sm:pb-14">
				<div className="mx-auto w-full max-w-6xl rounded-3xl border border-[#29405c] bg-[linear-gradient(145deg,#0f1a2d_0%,#0d1728_60%,#12233a_100%)] p-5 shadow-[0_22px_40px_rgba(3,10,26,0.5)] sm:p-7">
					<h2 className="font-display text-2xl text-white sm:text-3xl">Fortified Security &amp; IP Protection for Writers</h2>
					<p className="font-body mt-3 text-sm leading-relaxed text-[#b8c9dc] sm:text-base">
						At Ckript, we prioritize the integrity and security of the creative process. We understand that a writer's script is their most valuable intellectual property. Therefore, we provide:
					</p>

					<div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">
						{securityPoints.map((item, index) => (
							<ContentCard
								key={item.title}
								icon={index === 0 ? Lock : index === 1 ? ShieldCheck : Sparkles}
								title={item.title}
								description={item.description}
							/>
						))}
					</div>
				</div>
			</section>

			<section className="relative z-10 px-4 pb-10 sm:px-8 sm:pb-14">
				<div className="mx-auto w-full max-w-6xl rounded-3xl border border-[#29405c] bg-[linear-gradient(145deg,#101b2f_0%,#0f172a_60%,#13253d_100%)] p-5 shadow-[0_22px_40px_rgba(3,10,26,0.5)] sm:p-7">
					<h2 className="font-display text-2xl text-white sm:text-3xl">Intelligent Discovery for Producers &amp; Directors</h2>
					<p className="font-body mt-3 text-sm leading-relaxed text-[#b8c9dc] sm:text-base">
						For industry professionals, Ckript transforms the traditionally time-consuming process of script development into an efficient, data-driven workflow. We provide a tailored suite of tools powered by cutting-edge technology:
					</p>

					<div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">
						{discoveryPoints.map((item, index) => (
							<ContentCard
								key={item.title}
								icon={index === 0 ? Clapperboard : index === 1 ? BrainCircuit : Film}
								title={item.title}
								description={item.description}
							/>
						))}
					</div>
				</div>
			</section>

			<footer className="relative z-10 border-t border-[#1f2f45] bg-[linear-gradient(180deg,#0b1323_0%,#0a1020_100%)] px-4 py-8 sm:px-8 sm:py-10">
				<div className="mx-auto flex w-full max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
					<div>
						<p className="font-body mt-1 text-xs text-[#9cb1c9]">&copy; 2026 Ckript. All rights reserved.</p>
					</div>

					<div className="font-body flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#9cb1c9] sm:text-sm">
						<Link to="/about" className="transition-colors hover:text-white">About</Link>
						<Link to="/contact" className="transition-colors hover:text-white">Contact</Link>
						<Link to="/privacy-policy" className="transition-colors hover:text-white">Privacy Policy</Link>
						<Link to="/terms-of-service" className="transition-colors hover:text-white">Terms of Service</Link>
					</div>
				</div>
			</footer>

		</div>
	);
};

export default About;
